spring.application.name=api

spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM561073
spring.datasource.password=190903
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
